run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "!**/*_test.go"
        allow:
          - $gostd
          - github.com/gotd/td
          - github.com/joho/godotenv
          - gopkg.in/yaml.v3
          - golang.org/x/time/rate
          - tg-down/internal/config
          - tg-down/internal/logger
          - tg-down/internal/telegram
          - tg-down/internal/downloader
          - tg-down/internal/session
          - tg-down/internal/middleware/floodwait
          - tg-down/internal/middleware/ratelimit
          - tg-down/internal/retry
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: tg-down
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - exitAfterDefer
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '10'
      - '100'
      - '1000'
      - '1024'
    ignored-functions:
      - 'time.Sleep'
      - 'time.Duration'
      - 'make'
      - 'strconv.FormatInt'
      - 'strconv.ParseInt'

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - cmd/test-optimizations
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
    - path: cmd/test-optimizations/
      linters:
        - gocyclo
        - mnd
        - revive
    - path: cmd/
      linters:
        - gochecknoinits
    - text: "is unused"
      linters:
        - unused
    - text: "parameter .* seems to be unused"
      linters:
        - unparam
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0